### ISSUE TITLE
All requirements are installed and everything is on the correct version but it somehow keeps crashing

### ISSUE THREAD

**Issue by Geopardo12345** [skylorbeck/tokenablefurnaces#10]
[crash-2022-02-07_16.49.45-client.txt](https://github.com/Skylortrexler/tokenablefurnaces/files/8017311/crash-2022-02-07_16.49.45-client.txt)

**Comment by skylorbeck** [comment]
You need clothconfig. https://www.curseforge.com/minecraft/mc-mods/cloth-config/files
It's listed in the requirements for tokenable.
