### ISSUE TITLE
Chests working very strange imo

### ISSUE THREAD

**Issue by toffi3** [skylorbeck/tokenablefurnaces#11]
Okey so i've been testing your mod on afk piglin bartering farm and it seems for me that chests are working very strange
It's worth to mention that they are very laggy (20fps) but i think that's unfixable so it's fine but for some reason when i do hopper system like shown on the screen here
![2022-03-02_20 05 30](https://user-images.githubusercontent.com/84127414/156430815-3c416800-f626-44ea-92e2-777f98265f69.png)
the items are not in the last chest but they are all in the first one and when first 8 double chests are filled (not all of 16) hoppers start to fill second amethyst chest. For me it is very strange how they work and i have no clue is itsupposed to work like that or not. Also could you expand the config? I think it lacks from setting the amount of chests in one amethyst, netherite, diamond chest etc.

**Comment by skylorbeck** [comment]
I see whats happening here. Each double chest is two separate entities that talk to each other. The chest on the left is the one that contains all the data for the items in the first half, and the chest on the right contains the data for all the slots on the second half. This is vanilla behavior, however they should also be talking to each other for situations like this. Thanks for the report and I'll see what I can do.

**Comment by skylorbeck** [comment]
Oh also yeah the lag is because each double amethyst is like 800 slots and the system buckles a little when you get up that high without reworking vanilla code more in-depth.

**Comment by toffi3** [comment]
Is there any way to fix this lag?

**Comment by skylorbeck** [comment]
The chest weirdness should be fixed now.
