### ISSUE TITLE
duplication glitch

### ISSUE THREAD

**Issue by cosmo5001** [skylorbeck/tokenablefurnaces#12]
if I have an amethyst hopper trying to put items in a furnace while the furnace is full the hopper makes a new item to put in the furnace when there's room instead of moving an item
I do have a video but its too big to submit here

**Comment by skylorbeck** [comment]
Can you explain a little further? It's making a duplicate where?

**Comment by cosmo5001** [comment]
I have an auto smelting setup with a chest on top of an amethyst hopper on top of an amethyst furnace and whenever I am trying to smelt more than a full stack of anything and stick the items in the chest a full stack makes it into the furnace and any extra on top of the stack stays in the hopper but when the furnace smelts an item the number of items in the hopper stays the same and the furnace still has a full stack of items
