### ISSUE TITLE
Duping Glitch With any Inventory That gets Updated

### ISSUE THREAD

**Issue by christian123555** [skylorbeck/tokenablefurnaces#13]
Saw earlier about the issue that got opened a few days ago were any time a furnace got maxed out in its inventory with a full token hopper above with any storage above that it created a dupe glitch so that the inventory above nor the hopper ever lost items, but the furnace continued to produce smelted output. After some testing it is hopper sided, not the inventory on top the hopper, but if the inventory receiving the items is another chest or something simple it does not happen, it only happen when the inventory that is receiving the items is something being updated, like a furnace being updated by its smelt time, or even a dropper receiving a redstone update from a redstone clock, you can even see the dropper losing items in the slots but then its refilled from a unknown source while the hopper and original inventory remains untouched. This is on the newest update of the mod that was released yesterday as well as the newest skylib, no changes have been made to the config and no mods that inject into the vanilla code have been added.

**Comment by skylorbeck** [comment]
From the sounds of things, this is a different duplication issue. The previous issue was due to hoppers returning _all_ items if _any_ could not be inserted. This sounds like it is returning all items if any could not be received. Will investigate.

**Comment by skylorbeck** [comment]
https://github.com/Skylortrexler/SkyLib/commit/b72b57a7d60712bf07cb3154f6e78e73c820894b

Same bug, different method. Thanks for reporting!

**Comment by skylorbeck** [comment]
All you need to do is update Skylib to 1.3.26 and that should be live in few minutes.

**Comment by christian123555** [comment]
ok thanks will do

**Comment by christian123555** [comment]
it worker tested with the same method before of a dropper on a redstone clock while its completely full with a full amethyst hopper above and then a chest with the same items, chest is being took from and the hopper is losing inventory and the dropper is losing inventory, so no duping at all. Thank you for being fast with it i love your mod being so creative in actually doing smokers and blast furnaces as well as hoppers.
