### ISSUE TITLE
Crash when normal hopper points down to token hopper

### ISSUE THREAD

**Issue by thnzk** [skylorbeck/tokenablefurnaces#14]
When item gets transferred from normal hopper pointing down towards an upgraded token hopper, my game crash.
everytime i tried to get back in the world it crashes again. the only solution was to disable the mod and load the world back so the hoppers dissapear and redo the entire thing.

**Comment by skylorbeck** [comment]
Can't do anything without a crash log

**Comment by thnzk** [comment]
Here's crash report https://pastebin.com/CcvSUZuU. Thanks :)

**Comment by skylorbeck** [comment]
Thanks. Will work on it. Seems easy to fix.

**Comment by skylorbeck** [comment]
https://github.com/skylorbeck/SkyLib/commit/21117b3b8d0c9addc005eacc8ea26391ca55e85d fixed. Update skylib to 1.3.35

**Comment by skylorbeck** [comment]
It was a stupid casting error. Forgot to change what class was being casted.
