### ISSUE TITLE
Block loot tables not working

### ISSUE THREAD

**Issue by fowlerro** [skylorbeck/tokenablefurnaces#17]
When I place any block from your mod and then try to mine it (with required tool ofc), that block doesn't drop anything.
I think it's because wrongly named loot table json files, AFAIK they have to match block name and in your mod that doesn't seem to be the case.
With `/setblock` command, I see that every block name ends with `_block`, but your loot table files do not end with `_block`.

![image](https://user-images.githubusercontent.com/54778147/173233079-4bb4ab3b-2f95-4a45-b7bb-756431115bce.png)
![image](https://user-images.githubusercontent.com/54778147/173232614-5f182bf7-57ce-4677-9c62-1f39cb8993ee.png)

**Comment by skylorbeck** [comment]
Thanks for the report, if you check the git pushes you can see that I just did a major rewrite of the entire mod and these must have been forgotten https://github.com/skylorbeck/tokenablefurnaces/commit/f1a07285771d670ce0963185cf653fa1849c0ef0 
It's easy to miss things when you have pushes like this 
![image](https://user-images.githubusercontent.com/42103122/173959859-8d2d216d-bb52-4007-be4e-9d5a809b36ec.png)
