### ISSUE TITLE
FPS Drop with Large Double Chests

### ISSUE THREAD

**Issue by ProSabre** [skylorbeck/tokenablefurnaces#18]
Hi,

I'm not sure if this is a bug or just a limitation within Minecraft but I have noticed that I have a significant drop in FPS when I open my amethyst double chest which has a considerable amount of items in. I usually have a rock solid 120 fps in normal play, when I open the chest I drop to around 70ish fps. I should also mention that I have ruled REI out as the cause of this as I use the texture caching feature to boost performance.
I have provided some screenshots below:

_With Chest Closed_
![2022-07-07_17 40 15](https://user-images.githubusercontent.com/93554660/177827163-32efd809-1d80-43a7-bf3c-011669bb3d45.png)
.

_With Chest Open_
![2022-07-07_17 40 23](https://user-images.githubusercontent.com/93554660/177827352-6fd4c499-b507-4276-a43b-4b8ce10db776.png)

Kind Regards

**Comment by skylorbeck** [comment]
Yeah not much I can do about that without changing how vanilla handles slots. There are around 864 item stacks on screen + your inventory when you are in the massive storage chests.

**Comment by skylorbeck** [comment]
I've spent a dozen hours pouring over chest code and the only solution I can find is to implement my own UI code like the other large chest mods do, and I don't care enough to do that really.

**Comment by ProSabre** [comment]
Thanks for the response!
Aah, I thought that might have been the case in all fairness. Great mod though!
