### ISSUE TITLE
Allow third party download

### ISSUE THREAD

**Issue by drakosoldier298** [skylorbeck/tokenablefurnaces#19]
https://user-images.githubusercontent.com/30358222/178088898-eef02cd0-0984-40b8-b2af-91b3ba089603.png
This toggle allows polymc/multimc and other non curseforge launchers to download your curseforge mod, aka no more forcing users to play on curseforge launcher

**Comment by skylorbeck** [comment]
Direct your complaints to curseforge. They do not pay for downloads that aren't from their service. My hands are tied.
