### ISSUE TITLE
Curseforge Download for third party launchers

### ISSUE THREAD

**Issue by Merith-TK** [skylorbeck/tokenablefurnaces#20]
in relation to #19 

I have not once seen nor heard of anyone actually getting paid for downloads, 

I "own" CC:Restitched on curseforge
which has 22 times (`757,746` versus your `34,104`) the amount of downloads, and have not received an single penny of rewards, as that is only available to those who have requested (and have been allowed in) to the creator rewards program, which it does not appear you have been accepted in by information I can gather

Mind you, these download numbers are realistically, only tracked for downloads from the curseforge launcher, and the curseforge website, so the actual number of downloads I have is *many* more, 

If you do not wish to set the required setting to allow third party launchers to download the mod from curse (which is an single toggle), please also upload to [Modrinth]( https://modrinth.com/), so that launchers can download it from there as well, this will also help with people discovering your mod as more and more people are transitioning to modrinth

![image](https://user-images.githubusercontent.com/10422110/178092000-a91f6ae4-365a-4ce6-8e08-cf47f2e3e4ee.png)
It is an single switch that only affects you ***IF*** you are inside the creator rewards program, you are not getting paid at all

**Comment by skylorbeck** [comment]
I literally got paid $250 this month lol and I have 1.75m downloads

**Comment by skylorbeck** [comment]
Smh can't believe this guy coming here to be a prick and act like he's hot shit.

**Comment by skylorbeck** [comment]
![Screenshot_20220708-221002.png](https://user-images.githubusercontent.com/42103122/178092541-94ac92dc-2215-42c7-9978-153ddbd264e9.png)![Screenshot_20220708-221019.png](https://user-images.githubusercontent.com/42103122/178092544-082c3e57-2f1c-4c10-9c85-300c3bc4d44f.png)

Not that I needed to provide proof of my earnings to you, but go fuck yourself for being such a prick.
