### ISSUE TITLE
Chest names are untranslated inside inventories

### ISSUE THREAD

**Issue by SplendidAlakey** [skylorbeck/tokenablefurnaces#21]
**MC** 1.19.2
**FAPI** 0.60.0
**TFaS** 2.0.1

Example with an iron chest:

![2022-08-28_19 57 14](https://user-images.githubusercontent.com/86702831/187088131-34a2f610-563a-4d1c-9a64-6ddb6a2a4ea1.png)

Logs: https://gist.github.com/Footage2-Amply-Pounce/4d686844a9c1337468d3bd45f2fac537

**Comment by skylorbeck** [comment]
What language are you playing in?

**Comment by SplendidAlakey** [comment]
American English

**Comment by skylorbeck** [comment]
Alright. Something must be up with the Lang file then. What version of the mod are you on?

**Comment by SplendidAlakey** [comment]
Tokenables 2.0.1 and SkyLib 1.5.1

**Comment by SplendidAlakey** [comment]
I think I've found the issue, in the lang file you refer to it as `container.iron_chest`, but in game it's `container.ironchest` https://github.com/skylorbeck/tokenablefurnaces/blob/f33e820ad831e2aa3f94192ee37c4eb000e77647/src/main/resources/assets/tokenablefurnaces/lang/en_us.json#L107

All chests are affected, I think the other items are fine.

**Comment by SplendidAlakey** [comment]
Yep, just checked and confirmed it. Chests, barrels and shulkers are missing the underscore in their names, while open.

**Comment by skylorbeck** [comment]
Thanks!
