### ISSUE TITLE
Items in Tokenable Shulkers are Voided once Mined

### ISSUE THREAD

**Issue by aisukuma** [skylorbeck/tokenablefurnaces#4]
I put lots of items on an Iron Shulker can mined it then I placed it back and noticed all my items have disappeared. No visual glitch, the items have been deleted.

**Comment by skylorbeck** [comment]
Oh no! I'm sorry that happened to you. What were you using to break it?

**Comment by aisukuma** [comment]
Just an iron pickaxe. It was random items inside the shulker, so it wasn't really a loss but it did surprise me about the items being deleted after being mined.

Did more testing, all of the tokenable shulkers seemed to be bugged mining with any pickaxe.

**Comment by skylorbeck** [comment]
Thank you for the report. I have a feeling this is related to a change I made last week.

**Comment by Skylortrexler** [comment]
I can't replicate this, what tier shulker did you have?

**Comment by aisukuma** [comment]
[On mobile so I’m not sure if you posted the other message here].

In my survival world I had an iron shulker and mined it with an unenchanted iron pickaxe. If doing that have no issues with just SkyLib and Tokenable Furnaces, it might be a mod conflict.

**Comment by skylorbeck** [comment]
I was hoping you didn't see that comment. I immediately was able to replicate it after I posted that.

**Comment by skylorbeck** [comment]
please update both TFaS and SkyLib
