### ISSUE TITLE
Tokenable Storages shows item from first slot on tab / Tokenable Shulkers not having correct placements

### ISSUE THREAD

**Issue by aisukuma** [skylorbeck/tokenablefurnaces#5]
Hi! Sorry for being a bother but updating to the latest SkyLib (1.0.2) and TokenableFurnaces (1.1.2), whenever I place any item on the first slot of any tab for any tokenable storage, that item shows up on the tab. I am not sure if that is intentional but in the previous versions, it was not like that. It is not a game breaking bug, just a visual bug.

----------------------------------------

Also, when using any tokenable shulkers, they do not have any sideways or underside placements like regular shulkers. Whenever placed in any position, the tokenable shulkers are always facing upright. This issue has been present before the latest updates.

----------------------------------------

I am in not rush for this to get fixed! Just giving you a heads up about these and sorry for being a bother! I am enjoying this mod so far.

I'll provide screenshots of both these.
![2021-08-21_11 04 23](https://user-images.githubusercontent.com/22802219/130326338-94aacd65-f3af-4248-9d45-d10361df203a.png)
![2021-08-21_11 04 25](https://user-images.githubusercontent.com/22802219/130326339-d08c7152-5d23-4473-8197-3ca918d70684.png)
![2021-08-21_11 04 37](https://user-images.githubusercontent.com/22802219/130326340-5134b81e-be43-4d44-96ee-81bc33908257.png)
![2021-08-21_11 06 08](https://user-images.githubusercontent.com/22802219/130326341-b557730e-9401-45d5-8ad3-2512518535eb.png)
![2021-08-21_11 13 20](https://user-images.githubusercontent.com/22802219/130326342-8760dcd9-fd49-4885-a88f-73e105c72cb2.png)

**Comment by skylorbeck** [comment]
Item previews were actually added in one of the first updates. As for shulkers placement, I actually didn't know that was a thing they did. It's a bug for sure though as they should inherit default behavior.

**Comment by aisukuma** [comment]
The orientation of the shulker appears to be a visual bug. It places in the correct orientation but visual-wise, it appears upright.

Also, the tokenable shulkers disappear after being mined when there are no items in it. The shulkers will drop if there are items inside it.

**Comment by skylorbeck** [comment]
The Drop bug will be fixed in the next update, but the placement direction hasn't been yet. 

https://github.com/Skylortrexler/SkyLib/commit/2791252763ebfc2c120152f51a69c97b21afcb91
