### ISSUE TITLE
Crash from upgrading Diamond chest with Netherite token

### ISSUE THREAD

**Issue by NotAPotter** [skylorbeck/tokenablefurnaces#6]
Exactly as the title says. Both times this happened it took place in the nether, if that helps.

**Comment by skylorbeck** [comment]
Do you have a crash log? I can't replicate this. If you don't have a log, what is in the chest?

**Comment by NotAPotter** [comment]
Nothing was in the chest, and here's a [link to the crash report.](https://pastebin.com/wZaHZFFy)

**Comment by skylorbeck** [comment]
Thank you. I'll work on that as soon as I can.

**Comment by skylorbeck** [comment]
Seems to be a simple fix.
